var database = require('./database');
var Book = database.Book;

new Book({name: 'Genesis', cname: '創世記', shortName: 'Gen', amount: 50, order: 1}).save();
new Book({name: 'Exodus', cname: '出埃及記', shortName: 'Exo', amount: 40, order: 2}).save();
new Book({name: 'Leviticus', cname: '利未記', shortName: 'Lev', amount: 27, order: 3}).save();
new Book({name: 'Numbers', cname: '民數記', shortName: 'Num', amount: 36, order: 4}).save();
new Book({name: 'Deuteronomy', cname: '申命記', shortName: 'Deu', amount: 34, order: 5}).save();
new Book({name: 'Joshua', cname: '約書亞記', shortName: 'Jos', amount: 24, order: 6}).save();
new Book({name: 'Judges', cname: '士師記', shortName: 'Jug', amount: 21, order: 7}).save();
new Book({name: 'Ruth', cname: '路得記', shortName: 'Rut', amount: 4, order: 8}).save();
new Book({name: '1 Samuel', cname: '撒母耳記上', shortName: '1Sa', amount: 31, order: 9}).save();
new Book({name: '2 Samuel', cname: '撒母耳記下', shortName: '2Sa', amount: 24, order: 10}).save();
new Book({name: '1Kings', cname: '列王紀上', shortName: '1Ki', amount: 22, order: 11}).save();
new Book({name: '2Kings', cname: '列王紀下', shortName: '2Ki', amount: 25, order: 12}).save();
new Book({name: '1 Chronicles', cname: '歷代志上', shortName: '1Ch', amount: 29, order: 13}).save();
new Book({name: '2 Chronicles', cname: '歷代志下', shortName: '2Ch', amount: 36, order: 14}).save();
new Book({name: 'Ezra', cname: '以斯拉記', shortName: 'Ezr', amount: 10, order: 15}).save();
new Book({name: 'Nehemiah', cname: '尼希米記', shortName: 'Neh', amount: 13, order: 16}).save();
new Book({name: 'Esther', cname: '以斯帖記', shortName: 'Est', amount: 10, order: 17}).save();
new Book({name: 'Job', cname: '約伯記', shortName: 'Job', amount: 42, order: 18}).save();
new Book({name: 'Psalms', cname: '詩篇', shortName: 'Psm', amount: 150, order: 19}).save();
new Book({name: 'Proverbs', cname: '箴言', shortName: 'Pro', amount: 31, order: 20}).save();