var database = require('./database');
var Book = database.Book;

new Book({name: '2 Chronicles', cname: '歷代志下', shortName: '2Ch', amount: 36}).save();
new Book({name: 'Ezra', cname: '以斯拉記', shortName: 'Ezr', amount: 10}).save();
new Book({name: 'Nehemiah', cname: '尼希米記', shortName: 'Neh', amount: 13}).save();
new Book({name: 'Esther', cname: '以斯帖記', shortName: 'Est', amount: 10}).save();
new Book({name: 'Job', cname: '約伯記', shortName: 'Job', amount: 42}).save();
new Book({name: 'Psalms', cname: '詩篇', shortName: 'Psm', amount: 150}).save();
new Book({name: 'Proverbs', cname: '箴言', shortName: 'Pro', amount: 31}).save();
new Book({name: 'Ecclesiastes', cname: '傳道書', shortName: 'Ecc', amount: 12}).save();
new Book({name: 'Song of Songs', cname: '雅歌', shortName: 'Son', amount: 8}).save();
new Book({name: '2 Chronicles', cname: '歷代志下', shortName: '2Ch', amount: 36}).save();
new Book({name: 'Ezra', cname: '以斯拉記', shortName: 'Ezr', amount: 10}).save();
new Book({name: 'Nehemiah', cname: '尼希米記', shortName: 'Neh', amount: 13}).save();
new Book({name: 'Esther', cname: '以斯帖記', shortName: 'Est', amount: 10}).save();
new Book({name: 'Job', cname: '約伯記', shortName: 'Job', amount: 42}).save();
new Book({name: 'Psalms', cname: '詩篇', shortName: 'Psm', amount: 150}).save();
new Book({name: 'Proverbs', cname: '箴言', shortName: 'Pro', amount: 31}).save();
new Book({name: 'Ecclesiastes', cname: '傳道書', shortName: 'Ecc', amount: 12}).save();
new Book({name: 'Song of Songs', cname: '雅歌', shortName: 'Son', amount: 8}).save();
new Book({name: '2 Chronicles', cname: '歷代志下', shortName: '2Ch', amount: 36}).save();
new Book({name: 'Ezra', cname: '以斯拉記', shortName: 'Ezr', amount: 10}).save();
new Book({name: 'Nehemiah', cname: '尼希米記', shortName: 'Neh', amount: 13}).save();
new Book({name: 'Esther', cname: '以斯帖記', shortName: 'Est', amount: 10}).save();
new Book({name: 'Job', cname: '約伯記', shortName: 'Job', amount: 42}).save();
new Book({name: 'Psalms', cname: '詩篇', shortName: 'Psm', amount: 150}).save();
new Book({name: 'Proverbs', cname: '箴言', shortName: 'Pro', amount: 31}).save();
new Book({name: 'Ecclesiastes', cname: '傳道書', shortName: 'Ecc', amount: 12}).save();
new Book({name: 'Song of Songs', cname: '雅歌', shortName: 'Son', amount: 8}).save();
new Book({name: '2 Chronicles', cname: '歷代志下', shortName: '2Ch', amount: 36}).save();
new Book({name: 'Ezra', cname: '以斯拉記', shortName: 'Ezr', amount: 10}).save();
new Book({name: 'Nehemiah', cname: '尼希米記', shortName: 'Neh', amount: 13}).save();
new Book({name: 'Esther', cname: '以斯帖記', shortName: 'Est', amount: 10}).save();
new Book({name: 'Job', cname: '約伯記', shortName: 'Job', amount: 42}).save();
new Book({name: 'Psalms', cname: '詩篇', shortName: 'Psm', amount: 150}).save();
new Book({name: 'Proverbs', cname: '箴言', shortName: 'Pro', amount: 31}).save();
new Book({name: 'Ecclesiastes', cname: '傳道書', shortName: 'Ecc', amount: 12}).save();
new Book({name: 'Song of Songs', cname: '雅歌', shortName: 'Son', amount: 8}).save();
new Book({name: '2 Chronicles', cname: '歷代志下', shortName: '2Ch', amount: 36}).save();
new Book({name: 'Ezra', cname: '以斯拉記', shortName: 'Ezr', amount: 10}).save();
new Book({name: 'Nehemiah', cname: '尼希米記', shortName: 'Neh', amount: 13}).save();
new Book({name: 'Esther', cname: '以斯帖記', shortName: 'Est', amount: 10}).save();
new Book({name: 'Job', cname: '約伯記', shortName: 'Job', amount: 42}).save();
new Book({name: 'Psalms', cname: '詩篇', shortName: 'Psm', amount: 150}).save();
new Book({name: 'Proverbs', cname: '箴言', shortName: 'Pro', amount: 31}).save();
new Book({name: 'Ecclesiastes', cname: '傳道書', shortName: 'Ecc', amount: 12}).save();
new Book({name: 'Song of Songs', cname: '雅歌', shortName: 'Son', amount: 8}).save();
new Book({name: '2 Chronicles', cname: '歷代志下', shortName: '2Ch', amount: 36}).save();
new Book({name: 'Ezra', cname: '以斯拉記', shortName: 'Ezr', amount: 10}).save();
new Book({name: 'Nehemiah', cname: '尼希米記', shortName: 'Neh', amount: 13}).save();
new Book({name: 'Esther', cname: '以斯帖記', shortName: 'Est', amount: 10}).save();
new Book({name: 'Job', cname: '約伯記', shortName: 'Job', amount: 42}).save();
new Book({name: 'Psalms', cname: '詩篇', shortName: 'Psm', amount: 150}).save();
new Book({name: 'Proverbs', cname: '箴言', shortName: 'Pro', amount: 31}).save();
new Book({name: 'Ecclesiastes', cname: '傳道書', shortName: 'Ecc', amount: 12}).save();
new Book({name: 'Song of Songs', cname: '雅歌', shortName: 'Son', amount: 8}).save();